#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diploma
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bookstore")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void Insertgenres(genres instance);
    partial void Updategenres(genres instance);
    partial void Deletegenres(genres instance);
    partial void Insertcompleteorders(completeorders instance);
    partial void Updatecompleteorders(completeorders instance);
    partial void Deletecompleteorders(completeorders instance);
    partial void Insertorders(orders instance);
    partial void Updateorders(orders instance);
    partial void Deleteorders(orders instance);
    partial void Insertwebbookstore(webbookstore instance);
    partial void Updatewebbookstore(webbookstore instance);
    partial void Deletewebbookstore(webbookstore instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::diploma.Properties.Settings.Default.bookstoreConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<genres> genres
		{
			get
			{
				return this.GetTable<genres>();
			}
		}
		
		public System.Data.Linq.Table<completeorders> completeorders
		{
			get
			{
				return this.GetTable<completeorders>();
			}
		}
		
		public System.Data.Linq.Table<orders> orders
		{
			get
			{
				return this.GetTable<orders>();
			}
		}
		
		public System.Data.Linq.Table<webbookstore> webbookstore
		{
			get
			{
				return this.GetTable<webbookstore>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.genres")]
	public partial class genres : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _genrename;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OngenrenameChanging(string value);
    partial void OngenrenameChanged();
    #endregion
		
		public genres()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genrename", DbType="NVarChar(100)")]
		public string genrename
		{
			get
			{
				return this._genrename;
			}
			set
			{
				if ((this._genrename != value))
				{
					this.OngenrenameChanging(value);
					this.SendPropertyChanging();
					this._genrename = value;
					this.SendPropertyChanged("genrename");
					this.OngenrenameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.completeorders")]
	public partial class completeorders : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _bookname;
		
		private string _price;
		
		private System.Nullable<System.DateTime> _selltime;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnbooknameChanging(string value);
    partial void OnbooknameChanged();
    partial void OnpriceChanging(string value);
    partial void OnpriceChanged();
    partial void OnselltimeChanging(System.Nullable<System.DateTime> value);
    partial void OnselltimeChanged();
    #endregion
		
		public completeorders()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bookname", DbType="NVarChar(100)")]
		public string bookname
		{
			get
			{
				return this._bookname;
			}
			set
			{
				if ((this._bookname != value))
				{
					this.OnbooknameChanging(value);
					this.SendPropertyChanging();
					this._bookname = value;
					this.SendPropertyChanged("bookname");
					this.OnbooknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="NVarChar(100)")]
		public string price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_selltime", DbType="DateTime")]
		public System.Nullable<System.DateTime> selltime
		{
			get
			{
				return this._selltime;
			}
			set
			{
				if ((this._selltime != value))
				{
					this.OnselltimeChanging(value);
					this.SendPropertyChanging();
					this._selltime = value;
					this.SendPropertyChanged("selltime");
					this.OnselltimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.orders")]
	public partial class orders : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _ordernumber;
		
		private string _bookname;
		
		private string _price;
		
		private string _customername;
		
		private string _orderadress;
		
		private string _paymentmethod;
		
		private string _deliverymethod;
		
		private string _orderstatus;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnordernumberChanging(System.Nullable<int> value);
    partial void OnordernumberChanged();
    partial void OnbooknameChanging(string value);
    partial void OnbooknameChanged();
    partial void OnpriceChanging(string value);
    partial void OnpriceChanged();
    partial void OncustomernameChanging(string value);
    partial void OncustomernameChanged();
    partial void OnorderadressChanging(string value);
    partial void OnorderadressChanged();
    partial void OnpaymentmethodChanging(string value);
    partial void OnpaymentmethodChanged();
    partial void OndeliverymethodChanging(string value);
    partial void OndeliverymethodChanged();
    partial void OnorderstatusChanging(string value);
    partial void OnorderstatusChanged();
    #endregion
		
		public orders()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ordernumber", DbType="Int")]
		public System.Nullable<int> ordernumber
		{
			get
			{
				return this._ordernumber;
			}
			set
			{
				if ((this._ordernumber != value))
				{
					this.OnordernumberChanging(value);
					this.SendPropertyChanging();
					this._ordernumber = value;
					this.SendPropertyChanged("ordernumber");
					this.OnordernumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bookname", DbType="NVarChar(100)")]
		public string bookname
		{
			get
			{
				return this._bookname;
			}
			set
			{
				if ((this._bookname != value))
				{
					this.OnbooknameChanging(value);
					this.SendPropertyChanging();
					this._bookname = value;
					this.SendPropertyChanged("bookname");
					this.OnbooknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="NVarChar(100)")]
		public string price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customername", DbType="NVarChar(100)")]
		public string customername
		{
			get
			{
				return this._customername;
			}
			set
			{
				if ((this._customername != value))
				{
					this.OncustomernameChanging(value);
					this.SendPropertyChanging();
					this._customername = value;
					this.SendPropertyChanged("customername");
					this.OncustomernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderadress", DbType="NVarChar(100)")]
		public string orderadress
		{
			get
			{
				return this._orderadress;
			}
			set
			{
				if ((this._orderadress != value))
				{
					this.OnorderadressChanging(value);
					this.SendPropertyChanging();
					this._orderadress = value;
					this.SendPropertyChanged("orderadress");
					this.OnorderadressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymentmethod", DbType="NVarChar(100)")]
		public string paymentmethod
		{
			get
			{
				return this._paymentmethod;
			}
			set
			{
				if ((this._paymentmethod != value))
				{
					this.OnpaymentmethodChanging(value);
					this.SendPropertyChanging();
					this._paymentmethod = value;
					this.SendPropertyChanged("paymentmethod");
					this.OnpaymentmethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deliverymethod", DbType="NVarChar(100)")]
		public string deliverymethod
		{
			get
			{
				return this._deliverymethod;
			}
			set
			{
				if ((this._deliverymethod != value))
				{
					this.OndeliverymethodChanging(value);
					this.SendPropertyChanging();
					this._deliverymethod = value;
					this.SendPropertyChanged("deliverymethod");
					this.OndeliverymethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderstatus", DbType="NVarChar(100)")]
		public string orderstatus
		{
			get
			{
				return this._orderstatus;
			}
			set
			{
				if ((this._orderstatus != value))
				{
					this.OnorderstatusChanging(value);
					this.SendPropertyChanging();
					this._orderstatus = value;
					this.SendPropertyChanged("orderstatus");
					this.OnorderstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.webbookstore")]
	public partial class webbookstore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _bookname;
		
		private string _price;
		
		private string _descrip;
		
		private string _genre;
		
		private System.Nullable<int> _stock;
		
		private System.Nullable<System.DateTime> _releasedate;
		
		private System.Data.Linq.Binary _imagename;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnbooknameChanging(string value);
    partial void OnbooknameChanged();
    partial void OnpriceChanging(string value);
    partial void OnpriceChanged();
    partial void OndescripChanging(string value);
    partial void OndescripChanged();
    partial void OngenreChanging(string value);
    partial void OngenreChanged();
    partial void OnstockChanging(System.Nullable<int> value);
    partial void OnstockChanged();
    partial void OnreleasedateChanging(System.Nullable<System.DateTime> value);
    partial void OnreleasedateChanged();
    partial void OnimagenameChanging(System.Data.Linq.Binary value);
    partial void OnimagenameChanged();
    #endregion
		
		public webbookstore()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bookname", DbType="NVarChar(100)")]
		public string bookname
		{
			get
			{
				return this._bookname;
			}
			set
			{
				if ((this._bookname != value))
				{
					this.OnbooknameChanging(value);
					this.SendPropertyChanging();
					this._bookname = value;
					this.SendPropertyChanged("bookname");
					this.OnbooknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="NVarChar(100)")]
		public string price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descrip", DbType="NVarChar(1000)")]
		public string descrip
		{
			get
			{
				return this._descrip;
			}
			set
			{
				if ((this._descrip != value))
				{
					this.OndescripChanging(value);
					this.SendPropertyChanging();
					this._descrip = value;
					this.SendPropertyChanged("descrip");
					this.OndescripChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genre", DbType="NVarChar(100)")]
		public string genre
		{
			get
			{
				return this._genre;
			}
			set
			{
				if ((this._genre != value))
				{
					this.OngenreChanging(value);
					this.SendPropertyChanging();
					this._genre = value;
					this.SendPropertyChanged("genre");
					this.OngenreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock", DbType="Int")]
		public System.Nullable<int> stock
		{
			get
			{
				return this._stock;
			}
			set
			{
				if ((this._stock != value))
				{
					this.OnstockChanging(value);
					this.SendPropertyChanging();
					this._stock = value;
					this.SendPropertyChanged("stock");
					this.OnstockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_releasedate", DbType="Date")]
		public System.Nullable<System.DateTime> releasedate
		{
			get
			{
				return this._releasedate;
			}
			set
			{
				if ((this._releasedate != value))
				{
					this.OnreleasedateChanging(value);
					this.SendPropertyChanging();
					this._releasedate = value;
					this.SendPropertyChanged("releasedate");
					this.OnreleasedateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagename", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary imagename
		{
			get
			{
				return this._imagename;
			}
			set
			{
				if ((this._imagename != value))
				{
					this.OnimagenameChanging(value);
					this.SendPropertyChanging();
					this._imagename = value;
					this.SendPropertyChanged("imagename");
					this.OnimagenameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
